<a href="https://colab.research.google.com/github/Havynse/hys/blob/master/Copy_of_numpy_exercise(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY EXERCISE**

**1. Import Numpy**

In [0]:
import numpy as np

**2. Manually create a matrix**

Create a 3-by-5 matrix and print it out to the screen

In [0]:
import numpy as np 

a = np.array([[1,2,3,4,10],[4,5,6,7,9],[4,6,5,3,4]]) 
a.shape = (3,5) 
print (a)

[[ 1  2  3  4 10]
 [ 4  5  6  7  9]
 [ 4  6  5  3  4]]


**3. Manually create a vector**

Create a vector which has 10 elements and print it out to the screen

In [0]:
import numpy as np
vector = np.arange(1,11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


**4. Automatically create matrix**



1.   Automatically create a 3-by-5 matrix which has interger values in the range of [0, 100]
2.   Automatically create a 5-by-7 matrix which has interger values in the range of [0, 100]
3.   Print out the above 2 matricces to the screen
4.   Implementy matrix multiplication of the above 2 matrices and print the result to the screen (let us call this result matrixx is C)




In [2]:
import numpy as np
a = np.random.randint(0,100,size=(3,5))
b = np.random.randint(0,100,size=(5,7))
print(a)
print(b)
c = a.dot(b)
c

[[41 89 21 78 91]
 [11  0 85 79  6]
 [57 19 43 59 33]]
[[83 45 97 40 53 37 80]
 [57 45  6 49 89 60 60]
 [93 48 89 82 99 94 98]
 [35 29 14 93 39 54 89]
 [31  6 86 48 94  9 22]]


array([[15980,  9666, 15298, 19345, 23769, 13862, 19622],
       [11769,  6902, 10254, 15045, 12643, 12717, 16373],
       [12901,  7393, 13134, 13808, 14372, 10774, 15891]])

**5. Scalar multiplication**

Input a number fromm keyboard and multiply this number with the above matrix C and print the result to the screen

In [0]:
d = c * 4
c

array([[2964,  774,  936, 8370,  405, 5229, 1749],
       [  48, 2805, 2511,  816, 5490, 1320, 2772],
       [ 162, 3944, 2449, 1190, 1701, 1728,  403],
       [1728,   82,  323, 2627, 1073, 4275, 5124],
       [ 798, 2030,  240,  741, 2233,  324, 5452]])

**6. Automatically create vector**

Automattically create a vector at size of 7-by-1 which has values in the range of [-10, 30]. And multiply the C matrix with this vector. Print the result to the screen.

In [0]:
vec = np.random.randint(-10,30,size=(7,1))
vec

array([[28],
       [-5],
       [ 1],
       [29],
       [ 0],
       [ 9],
       [15]])

**7. Matrix slicing**



1.   Automatically create a matrix at size of 7-by-15
2.   Print out the first column of this matrix 
3.   Print out the third row of this matrix
4.   Print out the element at the second column and fourth row



In [0]:
import numpy as np 
e = np.random.randint(0,30,size=(7, 15))
e


array([[ 0,  3,  8,  7, 11,  1,  8, 27, 19,  4, 17, 28, 11, 16, 29],
       [16, 24, 19, 26, 16, 23, 10, 24,  3, 12,  7,  4, 28, 11,  4],
       [24,  3, 10, 16, 19,  4, 11, 23, 19, 10, 12,  5, 18,  2, 25],
       [ 2, 19, 13, 25,  7, 16, 20, 22, 27,  6, 20, 22,  7, 25, 28],
       [18, 28,  8, 20,  3,  2, 27,  0,  8, 11, 21,  4,  2, 10, 15],
       [ 9, 28, 19, 11, 20,  6, 14, 12, 19, 15,  8, 20, 16,  0, 13],
       [ 4,  3, 28, 25,  5, 10,  2, 22, 13, 21, 12,  1, 14,  7, 24]])

In [0]:
e[:,[0]]



array([[ 0],
       [16],
       [24],
       [ 2],
       [18],
       [ 9],
       [ 4]])

In [0]:
e[2:3]


array([[24,  3, 10, 16, 19,  4, 11, 23, 19, 10, 12,  5, 18,  2, 25]])

In [0]:
e[1][3]

26

**8. Matrix transposition**

Perform the matrix transposition of the matrix in question 7 and print out to the screen.

In [0]:
e = np.random.randint(0,30,size=(7, 15))
e.transpose()

array([[12, 28, 24, 14, 17, 24, 26],
       [21,  1, 22,  7, 13,  3, 25],
       [ 0, 24, 16,  5, 24, 11, 21],
       [ 4, 26, 11, 19,  5,  6, 23],
       [ 3, 24, 11, 14, 17, 29, 23],
       [20, 18, 26, 10,  3, 18, 13],
       [19, 21, 28, 26,  7,  9, 23],
       [ 9, 29, 27,  7, 21, 20, 28],
       [25,  1, 28, 18,  6, 13, 28],
       [11, 15, 11, 20, 25,  3,  6],
       [20, 25, 15,  9, 12,  3, 15],
       [16, 25, 24, 28, 24,  7, 22],
       [ 5,  9,  1, 13,  9,  2, 11],
       [18, 22,  6, 23,  0, 12, 24],
       [ 0,  8,  1, 27, 19, 21, 19]])

**9. Matrix addition**



1.   Automatically create 2 integer matrices whicch have values in the range of [-10, 30]
2.   Print them to the screen
3.   Perform matrix addition of the above 2 matrices and print the result to the screen. 



In [0]:
f = np.random.randint(-10,30,size=(3, 5))
g = np.random.randint(-10,30,size=(3, 5))
print(f)
print(g)

[[-1  0 10 28 10]
 [ 7 -2 22 27 10]
 [22  6 28 15 25]]
[[-1 -2 14 -9 -2]
 [-9 27 17 11  4]
 [ 7 27 13 -6 24]]


In [0]:
np.add(f,g)

array([[-2, -2, 24, 19,  8],
       [-2, 25, 39, 38, 14],
       [29, 33, 41,  9, 49]])